# Overview

## NVIDIA hardware and software

The Jetson hardware consists of a multi-core `arm64` CPU and a CUDA-compatible GPU. The smallest of the family, the 2 GB Jetson Nano, has four CPU cores, 2 GB of RAM, and an NVIDIA Maxwell GPU with 128 CUDA cores. The peak speed is 472 billion floating point operations per second (GFLOPS).

The largest, the Jetson AGX Xavier, has eight CPU cores, 32 GB of RAM, and a Volta GPU with 64 tensor cores and 512 CUDA cores. The peak speed of the AGX Xavier is 32 trillion operations per second.

The Jetson software is called [JetPack](https://developer.nvidia.com/embedded/jetpack). JetPack includes

-   [Linux for Tegra (L4T)](https://developer.nvidia.com/embedded/linux-tegra), a full Ubuntu 18.04 LTS "Bionic Beaver" desktop,
-   NVIDIA drivers,
-   compilers, linkers and libraries to access the onboard GPU in C/C++ and Python, and
-   a complete NVIDIA Docker runtime.

`edgyR` adds

-   An administrative user account `edgyr` with Linux `sudo` privileges. This account requires a password to log into RStudio Server, but can execute commands with `sudo` without re-entering the password.

-   R 4.0.3 compiled from upstream source,

-   RStudioⓇ Server 1.4.1103 compiled from upstream source,

-   R package development tools:

    -   [`devtools`](https://devtools.r-lib.org/),
    -   [`tidyverse`](https://www.tidyverse.org/),
    -   [`rmarkdown`](https://rmarkdown.rstudio.com/), [`bookdown`](https://bookdown.org/) and [`pkgdown`](https://pkgdown.r-lib.org/),
    -   [`shinyⓇ`](https://shiny.rstudio.com/),
    -   [`reticulate`](https://rstudio.github.io/reticulate/) Python interface,
    -   [`odbc`](https://db.rstudio.com/getting-started/connect-to-database) database connectivity.

-   the [Miniforge](https://github.com/conda-forge/miniforge) [conda-forge](https://conda-forge.org/) distribution,

-   an optimized Python data science stack:

    -   [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/)
    -   the [`cupy`](https://cupy.dev/) CUDA-optimized version of `numpy`,
    -   the [`cuSignal`](https://github.com/rapidsai/cusignal) CUDA-optimized digital signal processing library.

`edgyR` is distributed via Docker image at [`edgyr`](https://hub.docker.com/r/edgyr/edgyr). The image is based on [NVIDIA L4T Base](https://ngc.nvidia.com/catalog/containers/nvidia:l4t-base).

## Installers

Once you run the `edgyr` Docker image and sign in to RStudio, you can install additional software on the image using the shell scripts in the `Installers` directory. As of release 0.7.5, these are

-   audio.sh: installs the [ChucK](https://chuck.cs.princeton.edu/) and [CSound](https://csound.com/) audio synthesis languages and R packages for audio analysis and synthesis [@sueur2018sound].
-   authoring.sh: installs additional packages for R Markdown authoring.
-   bayes.sh: installs the packages used in [@mcelreath2020statistical].
-   julia.sh: installs the Julia language globally and `CUDA.jl` for the `edgyr` user.
-   test-julia.sh: tests a Julia install. This takes a long time.
-   pocl.sh: [Portable Computing Language](http://portablecl.org/docs/html/). This implements OpenCL version 1.2 and includes a CUDA backend.
-   pyarrow-cuda-git.sh: Creates a `conda` environment with [Apache Arrow](https://arrow.apache.org/) C++ libraries and the [PyArrow](https://arrow.apache.org/docs/python/) Python bindings. The CUDA options are supported, and the R `arrow` package is installed in the `edgyr` user R library.
-   pytorch-1.7.sh: Creates a `virtualenv` environment with the NVIDIA CUDA version of PyTorch 1.7, and installs `rTorch` in the `edgyr` user R library.
-   spatial.sh:installs R packages for geospatial data science. Most of them are documented in [Geocomputation with R](https://geocompr.robinlovelace.net/) [@lovelace2019geocomputation].
-   tensorflow-1.sh: Creates a `virtualenv` environment with the NVIDIA CUDA version of TensorFlow 1.15, and installs `keras` in the `edgyr` user R library.
-   tensorflow-2.sh: : Creates a `virtualenv` environment with the NVIDIA CUDA version of TensorFlow 2.3, and installs `keras` in the `edgyr` user R library.

## References
